-- Academy Branded Apparel
INSERT INTO products (name, description, price, category, stock, isActive, imageUrl, imageKey) VALUES
('Academy Performance T-Shirt', 'Premium moisture-wicking performance tee featuring The Academy logo. Perfect for training sessions and everyday wear. Lightweight, breathable fabric keeps you cool during intense workouts.', 2500, 'apparel', 50, 1, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 'tshirt-black'),
('Academy Hoodie', 'Comfortable fleece hoodie with embroidered Academy logo. Ideal for warm-ups and cool-downs. Features front pocket and adjustable drawstring hood.', 4500, 'apparel', 30, 1, 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800', 'hoodie-black'),
('Academy Training Shorts', 'High-performance athletic shorts with Academy branding. Moisture-wicking fabric with elastic waistband and side pockets. Perfect for training and games.', 3000, 'apparel', 40, 1, 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800', 'shorts-black'),
('Academy Long Sleeve Shirt', 'Comfortable long sleeve training shirt with Academy logo. Great for layering during cooler weather. Breathable fabric for all-day comfort.', 3500, 'apparel', 35, 1, 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800', 'longsleeve-black'),
('Academy Tank Top', 'Sleeveless performance tank with Academy branding. Maximum breathability for intense training sessions. Lightweight and comfortable fit.', 2200, 'apparel', 45, 1, 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800', 'tank-black');

-- Training Equipment
INSERT INTO products (name, description, price, category, stock, isActive, imageUrl, imageKey) VALUES
('Official Academy Basketball', 'Premium composite leather basketball featuring The Academy logo. Official size and weight. Perfect for training and games. Excellent grip and durability.', 3500, 'equipment', 25, 1, 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800', 'basketball'),
('Academy Training Bag', 'Spacious duffel bag with Academy branding. Multiple compartments for gear organization. Adjustable shoulder strap and reinforced handles. Water-resistant material.', 5500, 'equipment', 20, 1, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 'training-bag'),
('Academy Water Bottle', 'BPA-free 32oz water bottle with Academy logo. Leak-proof lid and easy-carry handle. Keeps drinks cold for hours. Essential for staying hydrated during training.', 1800, 'accessories', 60, 1, 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800', 'water-bottle'),
('Academy Wristbands (Pair)', 'Moisture-wicking wristbands with embroidered Academy logo. Sold as a pair. Comfortable elastic material. Perfect for keeping sweat away during games.', 1200, 'accessories', 50, 1, 'https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=800', 'wristbands'),
('Academy Headband', 'Non-slip headband with Academy branding. Keeps hair and sweat out of your face during training. Comfortable elastic material that stays in place.', 1500, 'accessories', 40, 1, 'https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=800', 'headband'),
('Academy Backpack', 'Durable backpack with Academy logo. Perfect for carrying gear to and from practice. Multiple pockets including laptop sleeve. Padded shoulder straps for comfort.', 4800, 'accessories', 25, 1, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 'backpack'),
('Academy Compression Sleeve', 'Arm compression sleeve with Academy branding. Provides support and improves circulation. Moisture-wicking fabric. Available in multiple sizes.', 2000, 'accessories', 35, 1, 'https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=800', 'compression-sleeve'),
('Academy Jump Rope', 'Speed jump rope with Academy logo on handles. Adjustable length. Perfect for conditioning and warm-ups. Lightweight and durable.', 1500, 'equipment', 30, 1, 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800', 'jump-rope'),
('Academy Resistance Bands Set', 'Set of 3 resistance bands with Academy branding. Light, medium, and heavy resistance levels. Great for strength training and injury prevention.', 2800, 'equipment', 20, 1, 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800', 'resistance-bands'),
('Academy Sweat Towel', 'Microfiber towel with embroidered Academy logo. Super absorbent and quick-drying. Perfect size for training sessions. Comes with carrying clip.', 1500, 'accessories', 45, 1, 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=800', 'towel');
