/**
 * Strix Governance Capability Registry
 *
 * Maps every governed admin route to its governance metadata.
 * Risk levels determine approval requirements:
 *   - critical: 2 approvals, different-approver required
 *   - high: 1 approval required
 *   - medium: auto-approved with evidence logging
 *   - low: auto-approved, evidence only
 *
 * Updated for Academy v1.7.1 (3,458-line routers.ts, 48 tables, 100 adminProcedure usages)
 */

export interface Capability {
  id: string;
  name: string;
  description: string;
  riskLevel: "critical" | "high" | "medium" | "low";
  routerPath: string;
  routerLine: number;
}

export const CAPABILITIES = {

  // ═══════════════════════════════════════════════════════════════
  // CRITICAL RISK — Privilege escalation, bulk notifications, financial
  // ═══════════════════════════════════════════════════════════════

  "admin.members.updateRole": {
    id: "admin.members.updateRole",
    name: "Update Member Role",
    description: "Change a member's role — privilege escalation vector",
    riskLevel: "critical" as const,
    routerPath: "admin.members.updateRole",
    routerLine: 881,
  },
  "dmAdmin.setUserRole": {
    id: "dmAdmin.setUserRole",
    name: "Set DM User Role",
    description: "Assign DM moderation role — privilege escalation",
    riskLevel: "critical" as const,
    routerPath: "dmAdmin.setUserRole",
    routerLine: 2129,
  },
  "roles.setRole": {
    id: "roles.setRole",
    name: "Set Extended Role (RBAC)",
    description: "Assign RBAC role (owner/admin/head_coach/etc.) — privilege escalation",
    riskLevel: "critical" as const,
    routerPath: "roles.setRole",
    routerLine: 3286,
  },
  "progressReports.sendToParents": {
    id: "progressReports.sendToParents",
    name: "Send Progress Reports to Parents",
    description: "Bulk email AI-generated reports to parents — mass communication",
    riskLevel: "critical" as const,
    routerPath: "progressReports.sendToParents",
    routerLine: 3366,
  },
  "leads.processNurture": {
    id: "leads.processNurture",
    name: "Process Nurture Campaigns",
    description: "Trigger bulk email nurture campaign — mass communication",
    riskLevel: "critical" as const,
    routerPath: "leads.processNurture",
    routerLine: 539,
  },
  "merchDrops.admin.sendNow": {
    id: "merchDrops.admin.sendNow",
    name: "Send Merch Drop Notification Now",
    description: "Immediately send push notifications for a merch drop",
    riskLevel: "critical" as const,
    routerPath: "merchDrops.admin.sendNow",
    routerLine: 2698,
  },

  // ═══════════════════════════════════════════════════════════════
  // HIGH RISK — Deletes, publishes, enrollment actions, financial
  // ═══════════════════════════════════════════════════════════════

  "admin.programs.delete": {
    id: "admin.programs.delete",
    name: "Delete Program",
    description: "Permanently remove a training program",
    riskLevel: "high" as const,
    routerPath: "admin.programs.delete",
    routerLine: 683,
  },
  "admin.announcements.publish": {
    id: "admin.announcements.publish",
    name: "Publish Announcement",
    description: "Make announcement visible to all members",
    riskLevel: "high" as const,
    routerPath: "admin.announcements.publish",
    routerLine: 715,
  },
  "admin.announcements.delete": {
    id: "admin.announcements.delete",
    name: "Delete Announcement",
    description: "Permanently remove an announcement",
    riskLevel: "high" as const,
    routerPath: "admin.announcements.delete",
    routerLine: 722,
  },
  "admin.schedules.delete": {
    id: "admin.schedules.delete",
    name: "Delete Schedule",
    description: "Remove a training session schedule",
    riskLevel: "high" as const,
    routerPath: "admin.schedules.delete",
    routerLine: 789,
  },
  "admin.members.removeProgram": {
    id: "admin.members.removeProgram",
    name: "Remove Member from Program",
    description: "Unenroll a member from a program",
    riskLevel: "high" as const,
    routerPath: "admin.members.removeProgram",
    routerLine: 863,
  },
  "chatAdmin.clearAll": {
    id: "chatAdmin.clearAll",
    name: "Clear All Chat Messages",
    description: "Permanently delete all messages in a chat room",
    riskLevel: "high" as const,
    routerPath: "chatAdmin.clearAll",
    routerLine: 961,
  },
  "gallery.admin.delete": {
    id: "gallery.admin.delete",
    name: "Delete Gallery Photo",
    description: "Remove a photo from the gallery",
    riskLevel: "high" as const,
    routerPath: "gallery.admin.delete",
    routerLine: 1046,
  },
  "shop.admin.products.delete": {
    id: "shop.admin.products.delete",
    name: "Delete Shop Product",
    description: "Remove a product from the merchandise store",
    riskLevel: "high" as const,
    routerPath: "shop.admin.products.delete",
    routerLine: 1231,
  },
  "shop.admin.campaigns.delete": {
    id: "shop.admin.campaigns.delete",
    name: "Delete Shop Campaign",
    description: "Remove a marketing campaign",
    riskLevel: "high" as const,
    routerPath: "shop.admin.campaigns.delete",
    routerLine: 1281,
  },
  "videos.admin.delete": {
    id: "videos.admin.delete",
    name: "Delete Video",
    description: "Remove a video from the content library",
    riskLevel: "high" as const,
    routerPath: "videos.admin.delete",
    routerLine: 1373,
  },
  "locations.admin.delete": {
    id: "locations.admin.delete",
    name: "Delete Location",
    description: "Remove a training facility location",
    riskLevel: "high" as const,
    routerPath: "locations.admin.delete",
    routerLine: 1786,
  },
  "coaches.admin.delete": {
    id: "coaches.admin.delete",
    name: "Delete Coach",
    description: "Remove a coach profile",
    riskLevel: "high" as const,
    routerPath: "coaches.admin.delete",
    routerLine: 1839,
  },
  "coaches.admin.assignments.delete": {
    id: "coaches.admin.assignments.delete",
    name: "Delete Coach Assignment",
    description: "Remove a coach-program assignment",
    riskLevel: "high" as const,
    routerPath: "coaches.admin.assignments.delete",
    routerLine: 1879,
  },
  "blogAdmin.publish": {
    id: "blogAdmin.publish",
    name: "Publish Blog Post",
    description: "Make blog post visible to all visitors",
    riskLevel: "high" as const,
    routerPath: "blogAdmin.publish",
    routerLine: 2364,
  },
  "blogAdmin.delete": {
    id: "blogAdmin.delete",
    name: "Delete Blog Post",
    description: "Permanently remove a blog post",
    riskLevel: "high" as const,
    routerPath: "blogAdmin.delete",
    routerLine: 2371,
  },
  "metrics.admin.delete": {
    id: "metrics.admin.delete",
    name: "Delete Athlete Metric",
    description: "Remove an athlete performance record",
    riskLevel: "high" as const,
    routerPath: "metrics.admin.delete",
    routerLine: 2563,
  },
  "showcases.admin.delete": {
    id: "showcases.admin.delete",
    name: "Delete Showcase",
    description: "Remove an athlete spotlight",
    riskLevel: "high" as const,
    routerPath: "showcases.admin.delete",
    routerLine: 2627,
  },
  "merchDrops.admin.delete": {
    id: "merchDrops.admin.delete",
    name: "Delete Merch Drop",
    description: "Remove a scheduled merch drop",
    riskLevel: "high" as const,
    routerPath: "merchDrops.admin.delete",
    routerLine: 2705,
  },
  "games.admin.deleteTrivia": {
    id: "games.admin.deleteTrivia",
    name: "Delete Trivia Question",
    description: "Remove a trivia question from the games hub",
    riskLevel: "high" as const,
    routerPath: "games.admin.deleteTrivia",
    routerLine: 2998,
  },
  "socialPosts.admin.delete": {
    id: "socialPosts.admin.delete",
    name: "Delete Social Post",
    description: "Remove a social media post from the gallery",
    riskLevel: "high" as const,
    routerPath: "socialPosts.admin.delete",
    routerLine: 3448,
  },
  "waitlist.enrollFromWaitlist": {
    id: "waitlist.enrollFromWaitlist",
    name: "Enroll from Waitlist",
    description: "Move a waitlisted member into a program — enrollment action",
    riskLevel: "high" as const,
    routerPath: "waitlist.enrollFromWaitlist",
    routerLine: 3100,
  },
  "waitlist.notifyNext": {
    id: "waitlist.notifyNext",
    name: "Notify Next on Waitlist",
    description: "Send notification to next person on waitlist",
    riskLevel: "high" as const,
    routerPath: "waitlist.notifyNext",
    routerLine: 3094,
  },
  "scheduleTemplates.delete": {
    id: "scheduleTemplates.delete",
    name: "Delete Schedule Template",
    description: "Remove a recurring schedule template",
    riskLevel: "high" as const,
    routerPath: "scheduleTemplates.delete",
    routerLine: 3204,
  },
  "scheduleTemplates.generate": {
    id: "scheduleTemplates.generate",
    name: "Generate Sessions from Template",
    description: "Bulk-create sessions from a schedule template",
    riskLevel: "high" as const,
    routerPath: "scheduleTemplates.generate",
    routerLine: 3211,
  },
  "billing.resolve": {
    id: "billing.resolve",
    name: "Resolve Billing Reminder",
    description: "Mark a billing/dunning reminder as resolved — financial action",
    riskLevel: "high" as const,
    routerPath: "billing.resolve",
    routerLine: 3231,
  },

  // ═══════════════════════════════════════════════════════════════
  // MEDIUM RISK — Creates, updates, content management
  // ═══════════════════════════════════════════════════════════════

  "admin.programs.create": {
    id: "admin.programs.create",
    name: "Create Program",
    description: "Add a new training program",
    riskLevel: "medium" as const,
    routerPath: "admin.programs.create",
    routerLine: 588,
  },
  "admin.programs.update": {
    id: "admin.programs.update",
    name: "Update Program",
    description: "Modify program details",
    riskLevel: "medium" as const,
    routerPath: "admin.programs.update",
    routerLine: 627,
  },
  "admin.announcements.create": {
    id: "admin.announcements.create",
    name: "Create Announcement",
    description: "Draft a new announcement",
    riskLevel: "medium" as const,
    routerPath: "admin.announcements.create",
    routerLine: 698,
  },
  "admin.schedules.create": {
    id: "admin.schedules.create",
    name: "Create Schedule",
    description: "Add a new training session schedule",
    riskLevel: "medium" as const,
    routerPath: "admin.schedules.create",
    routerLine: 737,
  },
  "admin.schedules.update": {
    id: "admin.schedules.update",
    name: "Update Schedule",
    description: "Modify schedule details",
    riskLevel: "medium" as const,
    routerPath: "admin.schedules.update",
    routerLine: 768,
  },
  "admin.members.assignProgram": {
    id: "admin.members.assignProgram",
    name: "Assign Member to Program",
    description: "Enroll a member in a program",
    riskLevel: "medium" as const,
    routerPath: "admin.members.assignProgram",
    routerLine: 827,
  },
  "admin.contacts.create": {
    id: "admin.contacts.create",
    name: "Create Contact",
    description: "Add a new contact record",
    riskLevel: "medium" as const,
    routerPath: "admin.contacts.create",
    routerLine: 899,
  },
  "gallery.admin.update": {
    id: "gallery.admin.update",
    name: "Update Gallery Photo",
    description: "Modify gallery photo metadata",
    riskLevel: "medium" as const,
    routerPath: "gallery.admin.update",
    routerLine: 1006,
  },
  "gallery.admin.upload": {
    id: "gallery.admin.upload",
    name: "Upload Gallery Photo",
    description: "Add a new photo to the gallery",
    riskLevel: "medium" as const,
    routerPath: "gallery.admin.upload",
    routerLine: 1027,
  },
  "gallery.admin.toggleVisibility": {
    id: "gallery.admin.toggleVisibility",
    name: "Toggle Gallery Visibility",
    description: "Show or hide a gallery photo",
    riskLevel: "medium" as const,
    routerPath: "gallery.admin.toggleVisibility",
    routerLine: 1054,
  },
  "shop.admin.products.create": {
    id: "shop.admin.products.create",
    name: "Create Shop Product",
    description: "Add a product to the store",
    riskLevel: "medium" as const,
    routerPath: "shop.admin.products.create",
    routerLine: 1185,
  },
  "shop.admin.products.update": {
    id: "shop.admin.products.update",
    name: "Update Shop Product",
    description: "Modify product details",
    riskLevel: "medium" as const,
    routerPath: "shop.admin.products.update",
    routerLine: 1206,
  },
  "shop.admin.campaigns.create": {
    id: "shop.admin.campaigns.create",
    name: "Create Shop Campaign",
    description: "Add a marketing campaign",
    riskLevel: "medium" as const,
    routerPath: "shop.admin.campaigns.create",
    routerLine: 1246,
  },
  "shop.admin.campaigns.update": {
    id: "shop.admin.campaigns.update",
    name: "Update Shop Campaign",
    description: "Modify campaign details",
    riskLevel: "medium" as const,
    routerPath: "shop.admin.campaigns.update",
    routerLine: 1263,
  },
  "videos.admin.create": {
    id: "videos.admin.create",
    name: "Create Video",
    description: "Add a video to the content library",
    riskLevel: "medium" as const,
    routerPath: "videos.admin.create",
    routerLine: 1336,
  },
  "videos.admin.update": {
    id: "videos.admin.update",
    name: "Update Video",
    description: "Modify video metadata",
    riskLevel: "medium" as const,
    routerPath: "videos.admin.update",
    routerLine: 1353,
  },
  "locations.admin.create": {
    id: "locations.admin.create",
    name: "Create Location",
    description: "Add a training facility location",
    riskLevel: "medium" as const,
    routerPath: "locations.admin.create",
    routerLine: 1739,
  },
  "locations.admin.update": {
    id: "locations.admin.update",
    name: "Update Location",
    description: "Modify location details",
    riskLevel: "medium" as const,
    routerPath: "locations.admin.update",
    routerLine: 1761,
  },
  "coaches.admin.create": {
    id: "coaches.admin.create",
    name: "Create Coach",
    description: "Add a new coach profile",
    riskLevel: "medium" as const,
    routerPath: "coaches.admin.create",
    routerLine: 1809,
  },
  "coaches.admin.update": {
    id: "coaches.admin.update",
    name: "Update Coach",
    description: "Modify coach profile details",
    riskLevel: "medium" as const,
    routerPath: "coaches.admin.update",
    routerLine: 1823,
  },
  "coaches.admin.assignments.create": {
    id: "coaches.admin.assignments.create",
    name: "Create Coach Assignment",
    description: "Assign a coach to a program",
    riskLevel: "medium" as const,
    routerPath: "coaches.admin.assignments.create",
    routerLine: 1865,
  },
  "blogAdmin.create": {
    id: "blogAdmin.create",
    name: "Create Blog Post",
    description: "Draft a new blog post",
    riskLevel: "medium" as const,
    routerPath: "blogAdmin.create",
    routerLine: 2310,
  },
  "blogAdmin.update": {
    id: "blogAdmin.update",
    name: "Update Blog Post",
    description: "Modify blog post content",
    riskLevel: "medium" as const,
    routerPath: "blogAdmin.update",
    routerLine: 2337,
  },
  "metrics.admin.record": {
    id: "metrics.admin.record",
    name: "Record Athlete Metric",
    description: "Log a new athlete performance measurement",
    riskLevel: "medium" as const,
    routerPath: "metrics.admin.record",
    routerLine: 2523,
  },
  "metrics.admin.update": {
    id: "metrics.admin.update",
    name: "Update Athlete Metric",
    description: "Modify an existing metric record",
    riskLevel: "medium" as const,
    routerPath: "metrics.admin.update",
    routerLine: 2542,
  },
  "showcases.admin.create": {
    id: "showcases.admin.create",
    name: "Create Showcase",
    description: "Add an athlete spotlight",
    riskLevel: "medium" as const,
    routerPath: "showcases.admin.create",
    routerLine: 2586,
  },
  "showcases.admin.update": {
    id: "showcases.admin.update",
    name: "Update Showcase",
    description: "Modify athlete spotlight details",
    riskLevel: "medium" as const,
    routerPath: "showcases.admin.update",
    routerLine: 2608,
  },
  "merchDrops.admin.create": {
    id: "merchDrops.admin.create",
    name: "Create Merch Drop",
    description: "Schedule a new merch drop",
    riskLevel: "medium" as const,
    routerPath: "merchDrops.admin.create",
    routerLine: 2664,
  },
  "merchDrops.admin.update": {
    id: "merchDrops.admin.update",
    name: "Update Merch Drop",
    description: "Modify merch drop details",
    riskLevel: "medium" as const,
    routerPath: "merchDrops.admin.update",
    routerLine: 2682,
  },
  "games.admin.createTrivia": {
    id: "games.admin.createTrivia",
    name: "Create Trivia Question",
    description: "Add a trivia question to the games hub",
    riskLevel: "medium" as const,
    routerPath: "games.admin.createTrivia",
    routerLine: 2962,
  },
  "games.admin.updateTrivia": {
    id: "games.admin.updateTrivia",
    name: "Update Trivia Question",
    description: "Modify a trivia question",
    riskLevel: "medium" as const,
    routerPath: "games.admin.updateTrivia",
    routerLine: 2980,
  },
  "scheduleTemplates.create": {
    id: "scheduleTemplates.create",
    name: "Create Schedule Template",
    description: "Add a recurring schedule template",
    riskLevel: "medium" as const,
    routerPath: "scheduleTemplates.create",
    routerLine: 3169,
  },
  "scheduleTemplates.update": {
    id: "scheduleTemplates.update",
    name: "Update Schedule Template",
    description: "Modify a schedule template",
    riskLevel: "medium" as const,
    routerPath: "scheduleTemplates.update",
    routerLine: 3185,
  },
  "socialPosts.admin.create": {
    id: "socialPosts.admin.create",
    name: "Create Social Post",
    description: "Add a social media post to the gallery",
    riskLevel: "medium" as const,
    routerPath: "socialPosts.admin.create",
    routerLine: 3401,
  },
  "socialPosts.admin.update": {
    id: "socialPosts.admin.update",
    name: "Update Social Post",
    description: "Modify social post details",
    riskLevel: "medium" as const,
    routerPath: "socialPosts.admin.update",
    routerLine: 3419,
  },
  "socialPosts.admin.toggleVisibility": {
    id: "socialPosts.admin.toggleVisibility",
    name: "Toggle Social Post Visibility",
    description: "Show or hide a social post",
    riskLevel: "medium" as const,
    routerPath: "socialPosts.admin.toggleVisibility",
    routerLine: 3435,
  },
  "socialPosts.admin.reorder": {
    id: "socialPosts.admin.reorder",
    name: "Reorder Social Posts",
    description: "Change the display order of social posts",
    riskLevel: "medium" as const,
    routerPath: "socialPosts.admin.reorder",
    routerLine: 3441,
  },

  // ═══════════════════════════════════════════════════════════════
  // LOW RISK — Read-only admin, attendance, booking status
  // ═══════════════════════════════════════════════════════════════

  "admin.contacts.markRead": {
    id: "admin.contacts.markRead",
    name: "Mark Contact Read",
    description: "Mark a contact submission as read",
    riskLevel: "low" as const,
    routerPath: "admin.contacts.markRead",
    routerLine: 943,
  },
  "admin.contacts.markResponded": {
    id: "admin.contacts.markResponded",
    name: "Mark Contact Responded",
    description: "Mark a contact submission as responded",
    riskLevel: "low" as const,
    routerPath: "admin.contacts.markResponded",
    routerLine: 950,
  },
  "coaches.updateBookingStatus": {
    id: "coaches.updateBookingStatus",
    name: "Update Booking Status",
    description: "Change a coach booking status",
    riskLevel: "low" as const,
    routerPath: "coaches.updateBookingStatus",
    routerLine: 1568,
  },
  "attendance.markAttendance": {
    id: "attendance.markAttendance",
    name: "Mark Attendance",
    description: "Record member attendance for a session",
    riskLevel: "low" as const,
    routerPath: "attendance.markAttendance",
    routerLine: 1660,
  },
  "attendance.updateAttendance": {
    id: "attendance.updateAttendance",
    name: "Update Attendance",
    description: "Modify an attendance record",
    riskLevel: "low" as const,
    routerPath: "attendance.updateAttendance",
    routerLine: 1710,
  },
} as const;

export type CapabilityId = keyof typeof CAPABILITIES;
